import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

/**
 * The web app is a separate package, so it gets a generated module rather than reaching
 * across package boundaries into artifacts/ at build time.
 */
const maras = JSON.parse(readFileSync("artifacts/contracts/Maras.sol/Maras.json", "utf8"));
const vault = JSON.parse(
  readFileSync("artifacts/contracts/templates/OwnedVault.sol/OwnedVault.json", "utf8"),
);
const proxy = JSON.parse(
  readFileSync("artifacts/contracts/templates/OwnedProxy.sol/OwnedProxy.json", "utf8"),
);

const deploymentPath = "deployments/baseSepolia.json";
const deployed = existsSync(deploymentPath)
  ? JSON.parse(readFileSync(deploymentPath, "utf8"))
  : undefined;

if (deployed === undefined) {
  console.warn(`${deploymentPath} not found — generating with a null address`);
}

const body = `// Generated by scripts/gen-web-abi.ts — do not edit.
import type { Abi, Address, Hex } from "viem";

export const MARAS_ADDRESS: Address | null = ${deployed ? `"${deployed.address}"` : "null"};
export const MARAS_BLOCK: number | null = ${deployed ? deployed.blockNumber : "null"};
export const CHAIN_ID = 84532;

export const marasAbi = ${JSON.stringify(maras.abi)} as const satisfies Abi;

export const ownedVaultAbi = ${JSON.stringify(vault.abi)} as const satisfies Abi;
export const ownedVaultBytecode = "${vault.bytecode}" as Hex;

export const ownedProxyAbi = ${JSON.stringify(proxy.abi)} as const satisfies Abi;
export const ownedProxyBytecode = "${proxy.bytecode}" as Hex;
`;

mkdirSync("web/lib", { recursive: true });
writeFileSync("web/lib/maras.generated.ts", body);
console.log(
  `Wrote web/lib/maras.generated.ts (address ${deployed ? deployed.address : "null"})`,
);
