import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

/**
 * viem needs a `const` ABI to narrow function names and argument tuples. A runtime
 * `JSON.parse` erases that, which makes every readContract/writeContract call untypeable,
 * so the node-side code imports this generated module instead.
 */
const maras = JSON.parse(readFileSync("artifacts/contracts/Maras.sol/Maras.json", "utf8"));
const vault = JSON.parse(
  readFileSync("artifacts/contracts/templates/OwnedVault.sol/OwnedVault.json", "utf8"),
);

const body = `// Generated by scripts/gen-node-abi.ts — do not edit.
import type { Abi, Hex } from "viem";

export const marasAbi = ${JSON.stringify(maras.abi)} as const satisfies Abi;

export const ownedVaultAbi = ${JSON.stringify(vault.abi)} as const satisfies Abi;
export const ownedVaultBytecode = "${vault.bytecode}" as Hex;
`;

mkdirSync("shared/generated", { recursive: true });
writeFileSync("shared/generated/abi.ts", body);
console.log("Wrote shared/generated/abi.ts");
