import { readFileSync, writeFileSync } from "node:fs";

/**
 * The hosted MCP server hands agents the grinder's source, since an agent connected only to the
 * MCP cannot clone the repository. Regenerate after touching anything in miner/grinder.
 */
const FILES = [
  "Cargo.toml",
  "Cargo.lock",
  "src/main.rs",
  "src/create3.rs",
  "src/target.rs",
  "src/rarity.rs",
  "words.txt",
];

const OUTPUT = "web/lib/mcp/grinder.generated.ts";

const entries = FILES.map(
  (path) => `  { path: ${JSON.stringify(path)}, contents: ${JSON.stringify(readFileSync(`miner/grinder/${path}`, "utf8"))} },`,
);

const body = `// Generated by scripts/gen-web-grinder.ts — do not edit.

export const GRINDER_FILES: ReadonlyArray<{ path: string; contents: string }> = [
${entries.join("\n")}
];
`;

writeFileSync(OUTPUT, body);
console.log(`Wrote ${OUTPUT} with ${FILES.length} files`);
