import { readFileSync, writeFileSync } from "node:fs";

/**
 * A grinder find is stored on chain as the hex spelling it matched, and a digit can stand for
 * more than one letter (1 is either i or l), so the English word cannot be worked back out of the
 * digits. The grinder's own dictionary already pairs each spelling with its word; the web app gets
 * that pairing as a module. Regenerate after scripts/gen-hex-words.ts.
 */
const SOURCE = "miner/grinder/words.txt";
const OUTPUT = "web/lib/hex-words.generated.ts";

const pairs = readFileSync(SOURCE, "utf8")
  .split("\n")
  .map((line) => line.trim().split(" "))
  .filter((parts): parts is [string, string] => parts.length === 2 && parts[0] !== parts[1]);

const body = `// Generated by scripts/gen-web-words.ts — do not edit.

export const ENGLISH_FOR_HEX: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(pairs))};
`;

writeFileSync(OUTPUT, body);
console.log(`Wrote ${pairs.length} spellings to ${OUTPUT}`);
